export const PRODUCT_CATEGORY_OPTIONS = [
  { value: 'prescription', label: 'Prescription Drugs' },
  { value: 'otc', label: 'Over-the-Counter (OTC)' },
  { value: 'vitamins', label: 'Vitamins & Supplements' },
  { value: 'medical-devices', label: 'Medical Devices' },
  { value: 'personal-care', label: 'Personal Care' },
  { value: 'baby-care', label: 'Baby & Child Care' },
  { value: 'first-aid', label: 'First Aid' },
  { value: 'diabetic-care', label: 'Diabetic Care' },
  { value: 'cosmetics', label: 'Cosmetics' },
  { value: 'laboratory', label: 'Laboratory' },
  { value: 'surgical', label: 'Surgical' },
  { value: 'dental', label: 'Dental' },
  { value: 'other', label: 'Other' },
] as const;

export const PRODUCT_UNIT_OPTIONS = [
  { value: 'tablet', label: 'Tablet' },
  { value: 'capsule', label: 'Capsule' },
  { value: 'bottle', label: 'Bottle' },
  { value: 'vial', label: 'Vial' },
  { value: 'ampoule', label: 'Ampoule' },
  { value: 'syringe', label: 'Syringe' },
  { value: 'tube', label: 'Tube' },
  { value: 'jar', label: 'Jar' },
  { value: 'pack', label: 'Pack' },
  { value: 'box', label: 'Box' },
  { value: 'card', label: 'Card' },
  { value: 'strip', label: 'Strip (Lab)' },
  { value: 'sachet', label: 'Sachet' },
  { value: 'kit', label: 'Kit' },
  { value: 'adult', label: 'Adult Size' },
  { value: 'children', label: 'Children Size' },
  { value: 'neonatal', label: 'Neonatal Size' },
  { value: 'pediatric', label: 'Pediatric Size' },
  { value: 'ml', label: 'Milliliter (ml)' },
  { value: 'mg', label: 'Milligram (mg)' },
  { value: 'g', label: 'Gram (g)' },
  { value: 'piece', label: 'Piece' },
] as const;

export const PACK_TYPE_OPTIONS = [
  { value: 'Box', label: 'Box' },
  { value: 'Card', label: 'Card' },
  { value: 'Pack', label: 'Pack' },
  { value: 'Blister', label: 'Blister' },
  { value: 'Bottle', label: 'Bottle' },
  { value: 'Tube', label: 'Tube' },
  { value: 'Vial', label: 'Vial' },
  { value: 'Ampoule', label: 'Ampoule' },
  { value: 'Sachet', label: 'Sachet' },
  { value: 'Kit', label: 'Kit' },
  { value: 'Strip', label: 'Strip (Lab)' },
  { value: 'Adult', label: 'Adult' },
  { value: 'Children', label: 'Children' },
  { value: 'Neonatal', label: 'Neonatal' },
] as const;
